const colorMode1 = {
  "Civil": "#46B45C",
  "Commercial": "orange",  // #FFA452
  "Military": "#F95959",
  "Government": "#349ab0",  //"#27576D"
  'mapHighlight': '#97ACB4' //'#97ACB4' //'#7FA7B0' // '#FFC04C'
};

const colorMode2 = {
  "all": "#ffffff",
  "+avg": "#29B6F6",
  "-avg": "#FFA726",
  "+": "#29B6F6",
  "-": "#FFA726",
  "p": "#29B6F6",  // alias to "+" because plus sign is an invalid symbol in css classes
  "n": "#FFA726",  // alias to "-" to have an alternative as "+" has
  "-5": "#E65100",
  "-4": "#F57C00",
  "-3": "#FF9800",
  "-2": "#FFB74D",
  "-1": "#FFE0B2",
  "0": "#ffffff",
  "+1": "#B3E5FC",
  "+2": "#4FC3F7",
  "+3": "#03A9F4",
  "+4": "#0288D1",
  "+5": "#01579B",
};

const cosmodromes = [
  {name: "Guiana Space Center", latitude: 5.2262115, longitude: -53.1423642, launches: 0},
  {name: "Cape Canaveral", latitude: 28.5141473, longitude: -80.6203127, launches: 0},
  {name: "Satish Dhawan Space Center", latitude: 13.7094402, longitude: 80.1520387, launches: 0},
  {name: "Vandenberg AFB", latitude: 34.7081599, longitude: -120.5921896, launches: 0},
  {name: "Taiyuan Launch Center", latitude: 38.8947201, longitude: 111.6754732, launches: 0},
  {name: "Plesetsk Cosmodrome", latitude: 62.9278719, longitude: 40.5736572, launches: 0},
  {name: "Dombarovsky Air Base", latitude: 51.0942292, longitude: 59.8399082, launches: 0},
  {name: "Jiuquan Satellite Launch Center", latitude: 40.9675, longitude: 100.278611, launches: 0},
  {name: "Xichang Satellite Launch Center", latitude: 28.246017, longitude: 102.026556, launches: 0},
  {name: "Tanegashima Space Center", latitude: 30.3747085, longitude: 130.9572727, launches: 0},
  {name: "Baikonur Cosmodrome", latitude: 45.8356119, longitude: 63.2572992, launches: 0}
];

const countryCodes = {
  "Afghanistan": "AFG",
  "Angola": "AGO",
  "Albania": "ALB",
  "United Arab Emirates": "ARE",
  "Argentina": "ARG",
  "Armenia": "ARM",
  "Antarctica": "ATA",
  "French Southern and Antarctic Lands": "ATF",
  "Australia": "AUS",
  "Austria": "AUT",
  "Azerbaijan": "AZE",
  "Burundi": "BDI",
  "Belgium": "BEL",
  "Benin": "BEN",
  "Burkina Faso": "BFA",
  "Bangladesh": "BGD",
  "Bulgaria": "BGR",
  "The Bahamas": "BHS",
  "Bosnia and Herzegovina": "BIH",
  "Belarus": "BLR",
  "Belize": "BLZ",
  "Bolivia": "BOL",
  "Brazil": "BRA",
  "Brunei": "BRN",
  "Bhutan": "BTN",
  "Botswana": "BWA",
  "Central African Republic": "CAF",
  "Canada": "CAN",
  "Switzerland": "CHE",
  "Chile": "CHL",
  "China": "CHN",
  "Ivory Coast": "CIV",
  "Cameroon": "CMR",
  "Democratic Republic of the Congo": "COD",
  "Republic of the Congo": "COG",
  "Colombia": "COL",
  "Costa Rica": "CRI",
  "Cuba": "CUB",
  "Northern Cyprus": "-99",
  "Cyprus": "CYP",
  "Czech Republic": "CZE",
  "Germany": "DEU",
  "Djibouti": "DJI",
  "Denmark": "DNK",
  "Dominican Republic": "DOM",
  "Algeria": "DZA",
  "Ecuador": "ECU",
  "Egypt": "EGY",
  "Eritrea": "ERI",
  "Spain": "ESP",
  "Estonia": "EST",
  "Ethiopia": "ETH",
  "Finland": "FIN",
  "Fiji": "FJI",
  "Falkland Islands": "FLK",
  "France": "FRA",
  "French Guiana": "GUF",
  "Gabon": "GAB",
  "United Kingdom": "GBR",
  "Georgia": "GEO",
  "Ghana": "GHA",
  "Guinea": "GIN",
  "Gambia": "GMB",
  "Guinea Bissau": "GNB",
  "Equatorial Guinea": "GNQ",
  "Greece": "GRC",
  "Greenland": "GRL",
  "Guatemala": "GTM",
  "Guyana": "GUY",
  "Honduras": "HND",
  "Croatia": "HRV",
  "Haiti": "HTI",
  "Hungary": "HUN",
  "Indonesia": "IDN",
  "India": "IND",
  "Ireland": "IRL",
  "Iran": "IRN",
  "Iraq": "IRQ",
  "Iceland": "ISL",
  "Israel": "ISR",
  "Italy": "ITA",
  "Jamaica": "JAM",
  "Jordan": "JOR",
  "Japan": "JPN",
  "Kazakhstan": "KAZ",
  "Kenya": "KEN",
  "Kyrgyzstan": "KGZ",
  "Cambodia": "KHM",
  "South Korea": "KOR",
  "Kosovo": "-99",
  "Kuwait": "KWT",
  "Laos": "LAO",
  "Lebanon": "LBN",
  "Liberia": "LBR",
  "Libya": "LBY",
  "Sri Lanka": "LKA",
  "Lesotho": "LSO",
  "Lithuania": "LTU",
  "Luxembourg": "LUX",
  "Latvia": "LVA",
  "Morocco": "MAR",
  "Moldova": "MDA",
  "Madagascar": "MDG",
  "Mexico": "MEX",
  "Macedonia": "MKD",
  "Mali": "MLI",
  "Myanmar": "MMR",
  "Montenegro": "MNE",
  "Mongolia": "MNG",
  "Mozambique": "MOZ",
  "Mauritania": "MRT",
  "Malawi": "MWI",
  "Malaysia": "MYS",
  "Namibia": "NAM",
  "New Caledonia": "NCL",
  "Niger": "NER",
  "Nigeria": "NGA",
  "Nicaragua": "NIC",
  "Netherlands": "NLD",
  "Norway": "NOR",
  "Nepal": "NPL",
  "New Zealand": "NZL",
  "Oman": "OMN",
  "Pakistan": "PAK",
  "Panama": "PAN",
  "Peru": "PER",
  "Philippines": "PHL",
  "Papua New Guinea": "PNG",
  "Poland": "POL",
  "Puerto Rico": "PRI",
  "North Korea": "PRK",
  "Portugal": "PRT",
  "Paraguay": "PRY",
  "Qatar": "QAT",
  "Romania": "ROU",
  "Russia": "RUS",
  "Rwanda": "RWA",
  "Western Sahara": "ESH",
  "Saudi Arabia": "SAU",
  "Sudan": "SDN",
  "South Sudan": "SSD",
  "Senegal": "SEN",
  "Solomon Islands": "SLB",
  "Sierra Leone": "SLE",
  "El Salvador": "SLV",
  "Somaliland": "-99",
  "Somalia": "SOM",
  "Republic of Serbia": "SRB",
  "Suriname": "SUR",
  "Slovakia": "SVK",
  "Slovenia": "SVN",
  "Sweden": "SWE",
  "Swaziland": "SWZ",
  "Syria": "SYR",
  "Chad": "TCD",
  "Togo": "TGO",
  "Thailand": "THA",
  "Tajikistan": "TJK",
  "Turkmenistan": "TKM",
  "East Timor": "TLS",
  "Trinidad and Tobago": "TTO",
  "Tunisia": "TUN",
  "Turkey": "TUR",
  "Taiwan": "TWN",
  "United Republic of Tanzania": "TZA",
  "Uganda": "UGA",
  "Ukraine": "UKR",
  "Uruguay": "URY",
  "United States of America": "USA",
  "USA": "USA",
  "Uzbekistan": "UZB",
  "Venezuela": "VEN",
  "Vietnam": "VNM",
  "Vanuatu": "VUT",
  "West Bank": "PSE",
  "Yemen": "YEM",
  "South Africa": "ZAF",
  "Zambia": "ZMB",
  "Zimbabwe": "ZWE"
}

// Monaco and Signapore have satellites, but are not displayed on this map.

export { colorMode1, colorMode2, countryCodes, cosmodromes };
